/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8-dev */

#ifndef PB_ERROR_PB_H_INCLUDED
#define PB_ERROR_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _ErrorResponse {
    int32_t code;
    pb_callback_t msg;
} ErrorResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define ErrorResponse_init_default               {0, {{NULL}, NULL}}
#define ErrorResponse_init_zero                  {0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define ErrorResponse_code_tag                   1
#define ErrorResponse_msg_tag                    2

/* Struct field encoding specification for nanopb */
#define ErrorResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    code,              1) \
X(a, CALLBACK, SINGULAR, STRING,   msg,               2)
#define ErrorResponse_CALLBACK pb_default_field_callback
#define ErrorResponse_DEFAULT NULL

extern const pb_msgdesc_t ErrorResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ErrorResponse_fields &ErrorResponse_msg

/* Maximum encoded size of messages (where known) */
/* ErrorResponse_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
