/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include "motor.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(MotorRequest, MotorRequest, AUTO)


PB_BIND(MotorResponse, MotorResponse, AUTO)




